express = require('express')
router = express.Router()

### GET users listing. ###

router.get '/', (req, res, next) ->
  res.send 'respond with a resource'
  return
module.exports = router

# ---
# generated by js2coffee 2.1.0
